# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_delete_usermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imgpro',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
