# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0004_user_imgpro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imgpro',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
