# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0005_auto_20180703_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
