# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0006_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
