# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0007_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
