# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-15 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0009_auto_20180710_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='profile_pic',
        ),
    ]
