# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0011_auto_20180715_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
