# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0017_auto_20180716_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/book_review/img/default-picture.png', upload_to='profile_image'),
        ),
    ]
