# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0020_auto_20180717_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_image/default-profile.png', upload_to='profile_image'),
        ),
    ]
