# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0025_auto_20180717_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, default='profile_image/default-book.png', upload_to='book_image'),
        ),
    ]
