# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0026_auto_20180717_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile_image/media/profile_image/default-profile.png', upload_to='profile_image'),
        ),
    ]
