# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0027_auto_20181128_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
