# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0028_auto_20181129_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, default='profile_image/default-book.png', null=True, upload_to='book_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile_image/media/profile_image/default-profile.png', upload_to='profile_image'),
        ),
    ]
