# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0030_auto_20190507_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, default='profile_image/default-book.png', null=True, upload_to='book_image'),
        ),
    ]
