# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0031_auto_20190507_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
