# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0033_auto_20190507_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
