# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0035_remove_book_book_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile/media/profile_image/default-profile.png', upload_to='profile_image'),
        ),
    ]
