# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0036_auto_20190507_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, default='/profile/media/profile_image/default-book.png', upload_to='book_image'),
        ),
    ]
