# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0047_auto_20190508_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_image/default-profile.png', upload_to='profile_image'),
        ),
    ]
