# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0051_auto_20190508_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_img',
        ),
    ]
